language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - docker

install:
  - pip install -U pip
  - pip install -U -r ci_requirements.txt

before_script:
  - docker run -d -p 3143:3143 -p 3993:3993 -p 3110:3110 -p 3995:3995 -p 3025:3025 -p 3465:3465 -e GREENMAIL_OPTS='-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled -Dgreenmail.verbose -Dgreenmail.users=login:password@domain.com' -t greenmail/standalone:latest
  - .build/check_ports.sh

script:
  - TEST_COMM=1 python -m coverage run --branch --source . -m unittest -v test.test_smtp_connection
  - TEST_COMM=1 TEST_PACKAGING=1 python -m coverage run --branch --source . -m unittest -v

after_success:
  - python -m coverage report --show-missing
  - codecov

after_script:
  - docker ps -q | xargs docker kill

notifications:
  slack:
    secure: "GUzJ5lMTuOoAVRHynLoCt/ihLblq1q4u19Xr/Twm+zBLrEcZKW3lmLDPCNVLjVlYKnxEA1XzVfxKg8v4I4dumWxAjj3zN69btIV/oLqcfA+oVSbjWzJ+xWQ1WX0+jmWQHp63XZGCHX7MqPVxqpbH1pyxv16eO9Z8R+hOkBpYRXJGKR1HhbPwi1v1tuz2rC6UkWyEFslm8f17Oa4hF3Q8gyZrgw8I+84T6Waaal3U1s1cd7tBDrMkTK0Q9oRns8zhy4xSdxCakdk5QXUoZx6F8u9FliQth8EVYGuXHZXPhA0ifGlFSRpxM4ealqVbjllqcZYC3bm5wY9TrBuegWyoCHTgLccWSpE3ZbCTjiAu1vrmL132opylNeQ+de/eXjcP5kXF8jWSTZ3ukq0f6H3DPk7hjVP7FuX/rmDSSF2elU13x7wJp7JRsQkjvjVUmMNFbwj920enym8IuXwVlGl5yvGTbxa0PIU6I6wmOROyP29OcM2f5xbbhCdOuYb1elIYoO0XQO9TpffHbCZO3TnDh1HMpwNNg1VnFDbQcifIaQtNEsS58poAvE8DXoN2tZyrYgv5qJIaHYzMJJ2CAbmSD02kjieChaeIvg6VyoavWMTIKGWbTuEIgCguWSPVasYl3EuIjPS8hSSDebcBRtmt0thUkCqMOXkl5/lc3+nHy/w="
  email: false
